package com.jay.login.common.handler

enum class UserErrorCode {
    USER_REGISTER_FAIL,
    USER_ALREADY_EXIST,
    INVALID_ID_FORMAT,
    INVALID_NAME_FORMAT,
    INVALID_PASSWORD_FORMAT,
    INVALID_EMAIL_FORMAT,
    INVALID_AUTHORITY,
    USER_UNKNOWN_ERROR
}